/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Home;

import javax.swing.JOptionPane;
import Config.ResendConfig;
import Controllers.AnimalController;
import Models.Animal;
import Models.User.PersistentUser;

/**
 *
 * @author ivant
 */
public class ConfirmAdoption extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmAdoption
     */
    private final Animal animal;
    private final PersistentUser user;
    private final AnimalController animalController;

    public ConfirmAdoption(Animal animal, PersistentUser user) {
        this.animalController = new AnimalController();
        this.animal = animal;
        this.user = user;
        initComponents();
        initConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameConfirm = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageConfirm = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        typeConfirm = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genereConfirm = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        breedConfirm = new javax.swing.JLabel();
        dateAConfirm = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        descriptionConfirm = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        cancelAdopBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Confirmar Adopción");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Información de la mascota");

        nameConfirm.setBackground(new java.awt.Color(255, 255, 255));
        nameConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameConfirm.setForeground(new java.awt.Color(0, 0, 0));
        nameConfirm.setText("Nombre:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad:");

        ageConfirm.setBackground(new java.awt.Color(255, 255, 255));
        ageConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageConfirm.setForeground(new java.awt.Color(0, 0, 0));
        ageConfirm.setText("Edad:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo:");

        typeConfirm.setBackground(new java.awt.Color(255, 255, 255));
        typeConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeConfirm.setForeground(new java.awt.Color(0, 0, 0));
        typeConfirm.setText("Tipo:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Género:");

        genereConfirm.setBackground(new java.awt.Color(255, 255, 255));
        genereConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genereConfirm.setForeground(new java.awt.Color(0, 0, 0));
        genereConfirm.setText("Género:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Raza:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Fecha de Ingreso:");

        breedConfirm.setBackground(new java.awt.Color(255, 255, 255));
        breedConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        breedConfirm.setForeground(new java.awt.Color(0, 0, 0));
        breedConfirm.setText("Raza:");

        dateAConfirm.setBackground(new java.awt.Color(255, 255, 255));
        dateAConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateAConfirm.setForeground(new java.awt.Color(0, 0, 0));
        dateAConfirm.setText("Raza:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Descripción:");

        descriptionConfirm.setBackground(new java.awt.Color(255, 255, 255));
        descriptionConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionConfirm.setForeground(new java.awt.Color(0, 0, 0));
        descriptionConfirm.setText("Descripción:");

        jLabel17.setBackground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("jLabel17");

        confirmBtn.setBackground(new java.awt.Color(0, 0, 0));
        confirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmBtn.setText("Confirmar Adopción");
        confirmBtn.setBorderPainted(false);
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelAdopBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelAdopBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelAdopBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelAdopBtn.setText("Cancelar");
        cancelAdopBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cancelAdopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdopBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameConfirm))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ageConfirm))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(breedConfirm)))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeConfirm))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genereConfirm))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateAConfirm))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descriptionConfirm))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelAdopBtn)
                .addGap(92, 92, 92)
                .addComponent(confirmBtn)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameConfirm)
                    .addComponent(jLabel7)
                    .addComponent(typeConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageConfirm)
                    .addComponent(jLabel9)
                    .addComponent(genereConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(breedConfirm))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(dateAConfirm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(descriptionConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(cancelAdopBtn))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initConfig() {

        animal.setSex(animal.getSex().equals("FEMALE") ? "Hembra" : "Macho");
            animal.setType(animal.getType().equals("DOG") ? "Perro" : "Gato");


        nameConfirm.setText(animal.getName());
        ageConfirm.setText(animal.getAge() + " años");
        typeConfirm.setText(animal.getType());
        genereConfirm.setText(animal.getSex());
        breedConfirm.setText(animal.getBreed());
        dateAConfirm.setText(animal.getDateOfAdmission());
        descriptionConfirm.setText(animal.getDescription());
    }
    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        boolean resultSaved = animalController.saveAnimalAdopted(animal.getId(), user.getId(), "");

        if (resultSaved) {
            JOptionPane.showMessageDialog(null, "El animal se adopto correctamente");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "El animal no se adopto correctamente");
            return;
        }

        ResendConfig resend = new ResendConfig();
        boolean result = resend.sendEmail(user.getEmail(), user.getFirts_name() + " " + user.getLast_name(), animal.getName(), user.getAddress());

        if (result) {
            JOptionPane.showMessageDialog(null, "El correo se envio correctamente");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "El correo no se envio correctamente");
        }

    }//GEN-LAST:event_confirmBtnActionPerformed

    private void cancelAdopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAdopBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelAdopBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageConfirm;
    private javax.swing.JLabel breedConfirm;
    private javax.swing.JButton cancelAdopBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel dateAConfirm;
    private javax.swing.JLabel descriptionConfirm;
    private javax.swing.JLabel genereConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameConfirm;
    private javax.swing.JLabel typeConfirm;
    // End of variables declaration//GEN-END:variables
}
